apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api-console-plugin
  namespace: openshift-console-plugin  # or another namespace
  labels:
    app: gateway-api-console-plugin
    app.kubernetes.io/component: gateway-api-console-plugin
    app.kubernetes.io/instance: gateway-api-console-plugin
    app.kubernetes.io/name: gateway-api-console-plugin
    app.kubernetes.io/part-of: gateway-api-console-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-api-console-plugin
  template:
    metadata:
      labels:
        app: gateway-api-console-plugin
        app.kubernetes.io/component: gateway-api-console-plugin
        app.kubernetes.io/instance: gateway-api-console-plugin
        app.kubernetes.io/name: gateway-api-console-plugin
        app.kubernetes.io/part-of: gateway-api-console-plugin
    spec:
      containers:
        - name: api-gateway-console-plugin
          image: quay.io/kuadrant/api-gateway-console-plugin:latest
          ports:
            - containerPort: 9443
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: plugin-serving-cert
              readOnly: true
              mountPath: /var/serving-cert
            - name: nginx-conf
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: plugin-serving-cert
          secret:
            secretName: plugin-serving-cert
            defaultMode: 420
        - name: nginx-conf
          configMap:
            name: nginx-conf
            defaultMode: 420
---
piVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: openshift-console-plugin
  labels:
    app: gateway-api-console-plugin
    app.kubernetes.io/component: gateway-api-console-plugin
    app.kubernetes.io/instance: gateway-api-console-plugin
    app.kubernetes.io/name: gateway-api-console-plugin
    app.kubernetes.io/part-of: gateway-api-console-plugin
data:
  nginx.conf: |
    error_log /dev/stdout;
    events {}
    http {
      access_log         /dev/stdout;
      include            /etc/nginx/mime.types;
      default_type       application/octet-stream;
      keepalive_timeout  65;

      server {
        listen              9443 ssl;
        listen              [::]:9443 ssl;
        ssl_certificate     /var/serving-cert/tls.crt;
        ssl_certificate_key /var/serving-cert/tls.key;

        location / {
          root                /usr/share/nginx/html;
        }
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: plugin-serving-cert
  name: api-gateway-console-plugin
  namespace: openshift-console-plugin
  labels:
    app: gateway-api-console-plugin
    app.kubernetes.io/component: gateway-api-console-plugin
    app.kubernetes.io/instance: gateway-api-console-plugin
    app.kubernetes.io/name: gateway-api-console-plugin
    app.kubernetes.io/part-of: gateway-api-console-plugin
spec:
  ports:
    - name: 9443-tcp
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    app: gateway-api-console-plugin
  type: ClusterIP
---
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: gateway-api-console-plugin
spec:
  displayName: 'API Gateway Console Plugin'
  i18n:
    loadType: Preload
  backend:
    type: Service
    service:
      name: gateway-api-console-plugin
      namespace: openshift-console-plugin
      port: 9443
      basePath: '/'
